[nixpacks]
phases.setup.nixPkgs = [
  "libnss3"
  "libatk"
  "libatk-bridge"
  "libcups"
  "libgbm"
  "libasound"
  "libpangocairo"
  "libxss"
  "libgtk3"
  "libxshmfence"
  "mesa"
  "glu"
  "chromium"
]
