[phases.setup]
nixPkgs = [
  "libnss3",
  "libatk",
  "libatk-bridge",
  "libcups",
  "libxshmfence",
  "libxss",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libgbm",
  "libgtk3",
  "libasound",
  "libglu"
]


